spring.application.name=orchestration-service
server.port=8087
temporal.target=localhost:7233
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
services.payment-url=http://localhost:8083
services.network-url=http://localhost:8084
services.fulfillment-url=http://localhost:8085
services.billing-url=http://localhost:8086
springdoc.swagger-ui.path=/swagger-ui.html
