spring.application.name=customer-service
server.port=8080

spring.mongodb.uri=mongodb://localhost:27017/customer_db

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always