package com.example.fulfillmentservice;
import com.example.fulfillmentservice.exception.ConflictException;import com.example.fulfillmentservice.model.*;import com.example.fulfillmentservice.repository.FulfillmentRepository;import com.example.fulfillmentservice.service.FulfillmentService;import java.time.Instant;import java.util.*;import org.junit.jupiter.api.*;import org.springframework.dao.DuplicateKeyException;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;
class FulfillmentServiceTests{
 private FulfillmentRepository repository;private FulfillmentService service;
 @BeforeEach void setup(){repository=mock(FulfillmentRepository.class);service=new FulfillmentService(repository,15,true);when(repository.save(any())).thenAnswer(i->i.getArgument(0));}
 @Test void createIsIdempotentForSameOrderAndPayload(){Fulfillment existing=fulfillment("order-1","customer-1","product-1",FulfillmentStatus.RECEIVED);when(repository.findByOrderId("order-1")).thenReturn(Optional.of(existing));assertSame(existing,service.create(new CreateFulfillmentRequest("order-1","customer-1","product-1")));verify(repository,never()).save(any());}
 @Test void createRejectsDifferentProductForExistingOrder(){when(repository.findByOrderId("order-1")).thenReturn(Optional.of(fulfillment("order-1","customer-1","product-1",FulfillmentStatus.RECEIVED)));assertThrows(ConflictException.class,()->service.create(new CreateFulfillmentRequest("order-1","customer-1","product-2")));}
 @Test void duplicateKeyRaceReturnsEquivalentWinner(){Fulfillment winner=fulfillment("order-1","customer-1","product-1",FulfillmentStatus.RECEIVED);when(repository.findByOrderId("order-1")).thenReturn(Optional.empty(),Optional.of(winner));when(repository.save(any())).thenThrow(new DuplicateKeyException("orderId_1"));assertSame(winner,service.create(new CreateFulfillmentRequest("order-1","customer-1","product-1")));}
 @Test void duplicateKeyRaceRejectsDifferentWinner(){Fulfillment winner=fulfillment("order-1","customer-1","product-2",FulfillmentStatus.RECEIVED);when(repository.findByOrderId("order-1")).thenReturn(Optional.empty(),Optional.of(winner));when(repository.save(any())).thenThrow(new DuplicateKeyException("orderId_1"));assertThrows(ConflictException.class,()->service.create(new CreateFulfillmentRequest("order-1","customer-1","product-1")));}
 @Test void processorMovesDispatchedFulfillmentToDelivered(){Fulfillment existing=fulfillment("order-1","customer-1","product-1",FulfillmentStatus.DISPATCHED);existing.setNextTransitionAt(Instant.now().minusSeconds(1));when(repository.findByStatusIn(any())).thenReturn(List.of(existing));service.process();assertEquals(FulfillmentStatus.DELIVERED,existing.getStatus());assertNotNull(existing.getDeliveredAt());assertNull(existing.getNextTransitionAt());verify(repository).save(existing);}
 @Test void processorDoesNothingWhenAutoAdvanceIsDisabled(){new FulfillmentService(repository,15,false).process();verify(repository,never()).findByStatusIn(any());}
 @Test void approveWalksDeliveryStepsInOrder(){Fulfillment existing=fulfillment("order-1","customer-1","product-1",FulfillmentStatus.RECEIVED);when(repository.findById("ful-1")).thenReturn(Optional.of(existing));assertEquals(FulfillmentStatus.PREPARING,service.approve("ful-1",null).getStatus());assertEquals(FulfillmentStatus.DISPATCHED,service.approve("ful-1",null).getStatus());assertNull(existing.getDeliveredAt());assertEquals(FulfillmentStatus.DELIVERED,service.approve("ful-1","Signed by customer").getStatus());assertNotNull(existing.getDeliveredAt());assertEquals("Signed by customer",existing.getStatusReason());assertThrows(ConflictException.class,()->service.approve("ful-1",null));}
 @Test void rejectFailsUndeliveredFulfillmentWithReason(){Fulfillment existing=fulfillment("order-1","customer-1","product-1",FulfillmentStatus.DISPATCHED);when(repository.findById("ful-1")).thenReturn(Optional.of(existing));assertEquals(FulfillmentStatus.FAILED,service.reject("ful-1","Lost in transit").getStatus());assertEquals("Lost in transit",existing.getStatusReason());assertThrows(ConflictException.class,()->service.reject("ful-1","again"));assertThrows(IllegalArgumentException.class,()->service.reject("ful-1"," "));}
 private Fulfillment fulfillment(String o,String c,String p,FulfillmentStatus s){Fulfillment f=new Fulfillment();f.setOrderId(o);f.setCustomerId(c);f.setProductId(p);f.setStatus(s);return f;}
}
