spring.application.name=fulfillment-service
server.port=8085
spring.mongodb.uri=mongodb://localhost:27022/fulfillment_db
fulfillment.transition-delay-seconds=15
springdoc.swagger-ui.path=/swagger-ui.html
