package com.example.tracking.controller;
import com.example.tracking.model.*;import com.example.tracking.repository.LifecycleEventRepository;import io.swagger.v3.oas.annotations.Operation;import java.time.Instant;import java.util.*;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/tracking/orders") public class TrackingController{
 private final LifecycleEventRepository repository; public TrackingController(LifecycleEventRepository repository){this.repository=repository;}
 @GetMapping("/{orderId}/events") @Operation(summary="Get ordered lifecycle history for an order") public List<LifecycleEvent>events(@PathVariable String orderId){return repository.findByOrderIdOrderByOccurredAtAsc(orderId);}
 @GetMapping @Operation(summary="Get one current lifecycle summary per tracked order") public List<OrderTrackingSummary> summaries(){Map<String,List<LifecycleEvent>> grouped=new HashMap<>();repository.findAll().forEach(e->grouped.computeIfAbsent(e.orderId(),ignored->new ArrayList<>()).add(e));return grouped.values().stream().map(this::summary).sorted(Comparator.comparing(OrderTrackingSummary::updatedAt,Comparator.nullsLast(Comparator.reverseOrder()))).toList();}
 private OrderTrackingSummary summary(List<LifecycleEvent> events){events.sort(Comparator.comparing(LifecycleEvent::occurredAt));LifecycleEvent last=events.get(events.size()-1);return new OrderTrackingSummary(last.orderId(),last.customerId(),latest(events,"ORDER_WORKFLOW"),latest(events,"PAYMENT"),latest(events,"ESIM_ACTIVATION"),latest(events,"FULFILLMENT"),latest(events,"BILLING"),last.occurredAt());}
 private String latest(List<LifecycleEvent> events,String type){return events.stream().filter(e->type.equals(e.eventType())).reduce((a,b)->b).map(LifecycleEvent::status).orElse("NOT_STARTED");}
}
