package com.example.networkservice;
import com.example.networkservice.exception.ConflictException;import com.example.networkservice.model.*;import com.example.networkservice.repository.ActivationRepository;import com.example.networkservice.service.ActivationService;import java.time.Instant;import java.util.*;import org.junit.jupiter.api.*;import org.springframework.dao.DuplicateKeyException;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;
class ActivationServiceTests{
 private ActivationRepository repository;private ActivationService service;
 @BeforeEach void setup(){repository=mock(ActivationRepository.class);service=new ActivationService(repository,30,true);when(repository.save(any())).thenAnswer(i->i.getArgument(0));}
 @Test void createIsIdempotentForSameOrderAndPayload(){Activation existing=activation("order-1","customer-1","plan-1",ActivationStatus.QUEUED);when(repository.findByOrderId("order-1")).thenReturn(Optional.of(existing));assertSame(existing,service.create(new CreateActivationRequest("order-1","customer-1","plan-1")));verify(repository,never()).save(any());}
 @Test void createRejectsDifferentPayloadForExistingOrder(){when(repository.findByOrderId("order-1")).thenReturn(Optional.of(activation("order-1","customer-1","plan-1",ActivationStatus.QUEUED)));assertThrows(ConflictException.class,()->service.create(new CreateActivationRequest("order-1","customer-1","plan-2")));}
 @Test void duplicateKeyRaceReturnsEquivalentWinner(){Activation winner=activation("order-1","customer-1","plan-1",ActivationStatus.QUEUED);when(repository.findByOrderId("order-1")).thenReturn(Optional.empty(),Optional.of(winner));when(repository.save(any())).thenThrow(new DuplicateKeyException("orderId_1"));assertSame(winner,service.create(new CreateActivationRequest("order-1","customer-1","plan-1")));}
 @Test void duplicateKeyRaceRejectsDifferentWinner(){Activation winner=activation("order-1","customer-2","plan-1",ActivationStatus.QUEUED);when(repository.findByOrderId("order-1")).thenReturn(Optional.empty(),Optional.of(winner));when(repository.save(any())).thenThrow(new DuplicateKeyException("orderId_1"));assertThrows(ConflictException.class,()->service.create(new CreateActivationRequest("order-1","customer-1","plan-1")));}
 @Test void processorActivatesReadyActivation(){Activation existing=activation("order-1","customer-1","plan-1",ActivationStatus.ACTIVATING);existing.setReadyAt(Instant.now().minusSeconds(1));when(repository.findByStatusIn(any())).thenReturn(List.of(existing));service.process();assertEquals(ActivationStatus.ACTIVE,existing.getStatus());assertNotNull(existing.getActivatedAt());verify(repository).save(existing);}
 @Test void processorDoesNothingWhenAutoAdvanceIsDisabled(){new ActivationService(repository,30,false).process();verify(repository,never()).findByStatusIn(any());}
 @Test void approveAdvancesOneStepAtATime(){Activation existing=activation("order-1","customer-1","plan-1",ActivationStatus.QUEUED);when(repository.findById("act-1")).thenReturn(Optional.of(existing));assertEquals(ActivationStatus.ACTIVATING,service.approve("act-1",null).getStatus());assertNull(existing.getActivatedAt());assertEquals(ActivationStatus.ACTIVE,service.approve("act-1","SIM provisioned").getStatus());assertNotNull(existing.getActivatedAt());assertEquals("SIM provisioned",existing.getStatusReason());assertThrows(ConflictException.class,()->service.approve("act-1",null));}
 @Test void rejectFailsActivationWithReason(){Activation existing=activation("order-1","customer-1","plan-1",ActivationStatus.ACTIVATING);when(repository.findById("act-1")).thenReturn(Optional.of(existing));assertEquals(ActivationStatus.FAILED,service.reject("act-1"," Network outage ").getStatus());assertEquals("Network outage",existing.getStatusReason());assertNotNull(existing.getStatusChangedAt());}
 @Test void rejectRequiresReasonAndPendingStep(){Activation existing=activation("order-1","customer-1","plan-1",ActivationStatus.ACTIVE);when(repository.findById("act-1")).thenReturn(Optional.of(existing));assertThrows(IllegalArgumentException.class,()->service.reject("act-1",""));assertThrows(ConflictException.class,()->service.reject("act-1","too late"));verify(repository,never()).save(any());}
 private Activation activation(String o,String c,String p,ActivationStatus s){Activation a=new Activation();a.setOrderId(o);a.setCustomerId(c);a.setPlanId(p);a.setStatus(s);return a;}
}
