spring.application.name=order-service
server.port=8082
spring.mongodb.uri=${SPRING_MONGODB_URI:mongodb://localhost:27019/order_db}
spring.data.mongodb.auto-index-creation=true
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://127.0.0.1:5173,http://localhost:5174,http://127.0.0.1:5174}
