server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location /api/orders { proxy_pass http://order-service:8082; }
  location /api/activations { proxy_pass http://network-service:8084; }
  location /api/fulfillments { proxy_pass http://fulfillment-service:8085; }
  location /api/subscriptions { proxy_pass http://billing-service:8086; }
  location /api/tracking { proxy_pass http://tracking-service:8088; }
  location / { try_files $uri $uri/ /index.html; }
}
