spring.application.name=billing-service
server.port=8086
spring.mongodb.uri=${SPRING_MONGODB_URI:mongodb://localhost:27023/billing_db}
spring.data.mongodb.auto-index-creation=true
services.payment-url=${SERVICES_PAYMENT_URL:http://localhost:8083}
services.network-url=${SERVICES_NETWORK_URL:http://localhost:8084}
services.fulfillment-url=${SERVICES_FULFILLMENT_URL:http://localhost:8085}
springdoc.swagger-ui.path=/swagger-ui.html
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
server.shutdown=graceful
