spring.application.name=billing-service
server.port=8086
spring.mongodb.uri=mongodb://localhost:27023/billing_db
services.network-url=http://localhost:8084
services.fulfillment-url=http://localhost:8085
springdoc.swagger-ui.path=/swagger-ui.html
