import{fireEvent,render,screen,waitFor}from'@testing-library/react';import{vi,it,expect,beforeEach}from'vitest';import{App}from'../App';
beforeEach(()=>vi.unstubAllGlobals());
it('shows the operations console',()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>[]}));render(<App/>);expect(screen.getByRole('heading',{name:'Order tracking'})).toBeInTheDocument()});
it('joins orders to the real tracking summary',async()=>{vi.stubGlobal('fetch',vi.fn(async(input:string|URL|Request)=>{const url=String(input);if(url==='/api/orders')return{ok:true,json:async()=>[{id:'order-1',customerId:'customer-1',productName:'Phone',storage:'128GB',planName:'Unlimited',total:10,status:'PENDING_PAYMENT',createdAt:'2026-01-01T00:00:00Z'}]};if(url==='/api/tracking/orders')return{ok:true,json:async()=>[{orderId:'order-1',customerId:'customer-1',workflowStatus:'WAITING_FOR_PAYMENT',paymentStatus:'PENDING',activationStatus:'NOT_STARTED',fulfillmentStatus:'NOT_STARTED',billingStatus:'NOT_STARTED',updatedAt:'2026-01-01T00:00:00Z'}]};return{ok:true,json:async()=>({status:'UP'})}}));render(<App/>);expect(await screen.findByText('order-1')).toBeInTheDocument();expect(await screen.findByText(/waiting for payment/i)).toBeInTheDocument();expect(await screen.findByText(/^pending$/i)).toBeInTheDocument()});

const pendingPayment={id:'pay-1',orderId:'order-9',customerId:'customer-1',amount:1328.99,currency:'EUR',transactionReference:'PAY-ABC',status:'PENDING',createdAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-01T00:00:00Z'};
function backend(){const posts:{url:string;body:unknown}[]=[];vi.stubGlobal('fetch',vi.fn(async(input:string|URL|Request,init?:RequestInit)=>{const url=String(input);if(init?.method==='POST'){posts.push({url,body:JSON.parse(String(init.body))});return{ok:true,json:async()=>({})}}if(url==='/api/payments')return{ok:true,json:async()=>[pendingPayment]};if(url.startsWith('/api/'))return{ok:true,json:async()=>[]};return{ok:true,json:async()=>({status:'UP'})}}));return posts}

it('approves a pending payment with an optional reason',async()=>{const posts=backend();render(<App/>);fireEvent.click(await screen.findByRole('button',{name:/Payments/}));fireEvent.click(await screen.findByRole('button',{name:'Approve payment'}));await waitFor(()=>expect(posts).toEqual([{url:'/api/payments/pay-1/approve',body:{reason:null}}]))});
it('requires a reason before rejecting',async()=>{const posts=backend();render(<App/>);fireEvent.click(await screen.findByRole('button',{name:/Payments/}));fireEvent.click(await screen.findByRole('button',{name:'Reject'}));expect(await screen.findByRole('alert')).toHaveTextContent('Enter a reason to reject.');expect(posts).toEqual([]);fireEvent.change(screen.getByLabelText('Reason for order order-9'),{target:{value:'Card declined by issuer'}});fireEvent.click(screen.getByRole('button',{name:'Reject'}));await waitFor(()=>expect(posts).toEqual([{url:'/api/payments/pay-1/reject',body:{reason:'Card declined by issuer'}}]))});
it('searches every column and sorts orders by date',async()=>{const order=(id:string,createdAt:string,planName:string)=>({id,customerId:'customer-1',productName:'Phone',storage:'1 TB',planName,total:10,status:'PENDING_PAYMENT',createdAt});vi.stubGlobal('fetch',vi.fn(async(input:string|URL|Request)=>{const url=String(input);if(url==='/api/orders')return{ok:true,json:async()=>[order('order-old','2026-01-01T00:00:00Z','Basic'),order('order-new','2026-02-01T00:00:00Z','Unlimited')]};if(url.startsWith('/api/'))return{ok:true,json:async()=>[]};return{ok:true,json:async()=>({status:'UP'})}}));render(<App/>);await screen.findByText('order-new');const ids=()=>screen.getAllByText(/^order-(old|new)$/).map(e=>e.textContent);expect(ids()).toEqual(['order-new','order-old']);fireEvent.click(screen.getByRole('button',{name:/Order ↓/}));expect(ids()).toEqual(['order-old','order-new']);fireEvent.change(screen.getByLabelText('Search'),{target:{value:'unlimited not started'}});expect(ids()).toEqual(['order-new'])});

const order1={id:'order-1',customerId:'customer-1',productName:'Phone',storage:'1 TB',planName:'Unlimited',total:1328.99,devicePrice:1299,monthlyPrice:29.99,status:'PENDING_PAYMENT',createdAt:'2026-01-01T00:00:00Z'};
function orderBackend(workflow:string){const posts:{url:string;body:unknown}[]=[];vi.stubGlobal('fetch',vi.fn(async(input:string|URL|Request,init?:RequestInit)=>{const url=String(input);if(init?.method==='POST'){posts.push({url,body:JSON.parse(String(init.body))});return{ok:true,status:200,json:async()=>({})}}
  if(url==='/api/orders/order-1')return{ok:true,status:200,json:async()=>order1};
  if(url==='/api/payments?orderId=order-1')return{ok:true,status:200,json:async()=>({...pendingPayment,orderId:'order-1'})};
  if(url==='/api/workflows/orders/order-1')return{ok:true,status:200,json:async()=>({status:workflow})};
  if(url==='/api/tracking/orders/order-1/events')return{ok:true,status:200,json:async()=>[{eventId:'e1',eventType:'PAYMENT',status:'PENDING',occurredAt:'2026-01-01T00:00:01Z'}]};
  if(url==='/api/subscriptions?customerId=customer-1&status=ACTIVE')return{ok:true,status:200,json:async()=>[{id:'sub-1',orderId:'order-1',customerId:'customer-1',planName:'Unlimited',monthlyAmount:29.99,status:'ACTIVE',createdAt:'2026-01-01T00:00:00Z',nextBillingAt:'2026-02-01T00:00:00Z'}]};
  if(url==='/api/tracking/orders')return{ok:true,status:200,json:async()=>[]};
  if(url.startsWith('/api/orders'))return{ok:true,status:200,json:async()=>[order1]};
  if(url.startsWith('/api/'))return{ok:false,status:404,json:async()=>({})};
  return{ok:true,status:200,json:async()=>({status:'UP'})}}));return posts}

it('opens a single order page where every step can be actioned and the order cancelled',async()=>{window.location.hash='';const posts=orderBackend('WAITING_FOR_PAYMENT');render(<App/>);fireEvent.click(await screen.findByRole('link',{name:'order-1'}));
  expect(await screen.findByRole('heading',{name:'Order details'})).toBeInTheDocument();expect(await screen.findByRole('heading',{name:'1. Payment'})).toBeInTheDocument();expect(screen.getByText('Created once payment is approved.')).toBeInTheDocument();
  fireEvent.click(screen.getByRole('button',{name:'Approve payment'}));await waitFor(()=>expect(posts[0]).toEqual({url:'/api/payments/pay-1/approve',body:{reason:null}}));
  fireEvent.click(screen.getByRole('button',{name:'Cancel order…'}));fireEvent.click(screen.getByRole('button',{name:'Confirm cancellation'}));expect(await screen.findByText('Enter a reason for cancelling.')).toBeInTheDocument();
  fireEvent.change(screen.getByLabelText('Cancellation reason'),{target:{value:'Customer request'}});fireEvent.click(screen.getByRole('button',{name:'Confirm cancellation'}));await waitFor(()=>expect(posts[1]).toEqual({url:'/api/workflows/orders/order-1/cancel',body:{reason:'Customer request'}}));window.location.hash=''});
it('lets an agent cancel an order whose workflow never started',async()=>{window.location.hash='#/orders/order-1';const posts=orderBackend('NOT_STARTED');render(<App/>);fireEvent.click(await screen.findByRole('button',{name:'Cancel order…'}));fireEvent.change(screen.getByLabelText('Cancellation reason'),{target:{value:'Stale order'}});fireEvent.click(screen.getByRole('button',{name:'Confirm cancellation'}));await waitFor(()=>expect(posts).toEqual([{url:'/api/workflows/orders/order-1/cancel',body:{reason:'Stale order'}}]));expect(screen.queryByRole('button',{name:'Approve payment'})).not.toBeInTheDocument();window.location.hash=''});
it('offers subscription cancellation instead once the order is complete',async()=>{window.location.hash='#/orders/order-1';orderBackend('COMPLETED');render(<App/>);expect(await screen.findByRole('heading',{name:'1. Payment'})).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Cancel order…'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Approve payment'})).not.toBeInTheDocument();window.location.hash=''});
it('finds a customer\'s active subscriptions from the billing tab',async()=>{window.location.hash='';orderBackend('COMPLETED');render(<App/>);fireEvent.click(await screen.findByRole('button',{name:/Billing/}));fireEvent.change(await screen.findByLabelText('Customer ID'),{target:{value:' customer-1 '}});fireEvent.click(screen.getByRole('button',{name:'Search'}));expect(await screen.findByText(/1 active subscription for customer customer-1/)).toBeInTheDocument();expect(screen.getByRole('link',{name:'order-1'})).toHaveAttribute('href','#/orders/order-1')});

function invoicingBackend(){const sent:{url:string;method:string;body:unknown}[]=[];vi.stubGlobal('fetch',vi.fn(async(input:string|URL|Request,init?:RequestInit)=>{const url=String(input);
  if(init?.method==='POST'||init?.method==='PUT'){sent.push({url,method:init.method,body:JSON.parse(String(init.body))});if(url==='/api/billing-schedule')return{ok:true,status:200,json:async()=>({enabled:false,runTime:'06:30:00',zone:'Europe/Dublin',updatedAt:'2026-01-01T00:00:00Z'})};return{ok:true,status:202,json:async()=>({runId:7,executionId:9,status:'STARTING',counts:null})}}
  if(url.startsWith('/api/billing-runs/preview'))return{ok:true,status:200,json:async()=>({runDate:'2026-09-30',subscriptions:2,total:29.99,currency:'EUR',lines:[{subscriptionId:'s1',orderId:'order-1',customerId:'customer-1',planName:'Unlimited',billingDay:28,periodStart:'2026-09-30',periodEnd:'2026-10-28',prorated:true,netAmount:22.76,vatAmount:5.23,totalAmount:27.99},{subscriptionId:'s2',orderId:'order-2',customerId:'customer-2',planName:'Unlimited',billingDay:15,periodStart:'2026-09-15',periodEnd:'2026-10-15',prorated:false,netAmount:24.38,vatAmount:5.61,totalAmount:29.99,existingInvoice:'INV-2026-000001'}]})};
  if(url==='/api/billing-runs')return{ok:true,status:200,json:async()=>[{runId:3,executionId:4,runDate:'2026-09-29',trigger:'SCHEDULED',status:'COMPLETED',startedAt:'2026-09-29T02:00:00Z',counts:{total:5,pending:0,invoiced:4,failed:1}}]};
  if(url==='/api/billing-schedule')return{ok:true,status:200,json:async()=>({enabled:true,runTime:'02:00:00',zone:'Europe/Dublin',nextRunAt:'2026-10-01T01:00:00Z',updatedAt:'2026-01-01T00:00:00Z'})};
  if(url.startsWith('/api/'))return{ok:true,status:200,json:async()=>[]};
  return{ok:true,status:200,json:async()=>({status:'UP'})}}));return sent}

it('plans a run with a preview, then starts it, from the Invoicing tab',async()=>{window.location.hash='';const sent=invoicingBackend();render(<App/>);fireEvent.click(await screen.findByRole('button',{name:'Invoicing'}));
  expect(await screen.findByText('#3')).toBeInTheDocument();
  fireEvent.change(screen.getByLabelText('Run date'),{target:{value:'2026-09-30'}});fireEvent.click(screen.getByRole('button',{name:'Preview'}));
  expect(await screen.findByText(/1 already invoiced/)).toBeInTheDocument();expect(screen.getByText('already INV-2026-000001')).toBeInTheDocument();expect(screen.getByText('prorated')).toBeInTheDocument();
  fireEvent.click(screen.getByRole('button',{name:'Run now'}));await waitFor(()=>expect(sent).toEqual([{url:'/api/billing-runs',method:'POST',body:{runDate:'2026-09-30'}}]));expect(await screen.findByText('Run #7 started for 2026-09-30.')).toBeInTheDocument()});
it('only previews future dates and saves the daily schedule',async()=>{window.location.hash='';const sent=invoicingBackend();render(<App/>);fireEvent.click(await screen.findByRole('button',{name:'Invoicing'}));
  fireEvent.change(await screen.findByLabelText('Run date'),{target:{value:'2999-01-01'}});expect(screen.getByRole('button',{name:'Run now'})).toBeDisabled();
  fireEvent.click(await screen.findByLabelText(/Run automatically/));fireEvent.change(screen.getByLabelText(/Run time/),{target:{value:'06:30'}});fireEvent.click(screen.getByRole('button',{name:'Save schedule'}));
  await waitFor(()=>expect(sent).toEqual([{url:'/api/billing-schedule',method:'PUT',body:{enabled:false,runTime:'06:30'}}]));expect(await screen.findByText(/Paused/)).toBeInTheDocument()});
