spring.application.name=product-service
server.port=8081
spring.mongodb.uri=mongodb://localhost:27018/product_db
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
springdoc.swagger-ui.path=/swagger-ui.html
