name: subscription-web-ui

services:
  web-ui:
    build: .
    container_name: web-ui
    restart: unless-stopped
    ports:
      - "5173:80"
    labels:
      com.datadoghq.tags.env: "${DD_ENV:-test}"
      com.datadoghq.tags.service: "web-ui"
      com.datadoghq.tags.version: "${APP_VERSION:-manual}"
      com.datadoghq.ad.logs: >-
        [{"source":"nginx","service":"web-ui"}]
    networks:
      - subscription-platform

networks:
  subscription-platform:
    external: true
    name: subscription-platform
