package com.example.billingservice;
import com.example.billingservice.exception.ConflictException;import com.example.billingservice.model.*;import com.example.billingservice.repository.SubscriptionRepository;import com.example.billingservice.service.*;import java.math.BigDecimal;import java.util.*;import org.junit.jupiter.api.*;import org.springframework.dao.DuplicateKeyException;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;
class BillingServiceTests{
 private SubscriptionRepository repository;private DependencyClient dependencies;private BillingService service;
 @BeforeEach void setup(){repository=mock(SubscriptionRepository.class);dependencies=mock(DependencyClient.class);service=new BillingService(repository,dependencies);when(repository.save(any())).thenAnswer(i->i.getArgument(0));when(dependencies.activation(anyString())).thenReturn(new DependencyClient.DependencyState(null,"UNAVAILABLE"));when(dependencies.fulfillment(anyString())).thenReturn(new DependencyClient.DependencyState(null,"UNAVAILABLE"));}
 @Test void createIsIdempotentForSameOrderAndPayload(){CreateSubscriptionRequest request=request("Basic");Subscription existing=subscription(request,BillingStatus.WAITING_FOR_ACTIVATION);when(repository.findByOrderId("order-1")).thenReturn(Optional.of(existing));assertSame(existing,service.create(request));verify(repository,never()).save(any());}
 @Test void createRejectsDifferentPlanForExistingOrder(){when(repository.findByOrderId("order-1")).thenReturn(Optional.of(subscription(request("Basic"),BillingStatus.WAITING_FOR_ACTIVATION)));assertThrows(ConflictException.class,()->service.create(request("Premium")));}
 @Test void reconciliationOnlyMarksReadyAndNeverStartsBilling(){Subscription existing=subscription(request("Basic"),BillingStatus.WAITING_FOR_FULFILLMENT);when(repository.findByStatusIn(any())).thenReturn(List.of(existing));dependenciesComplete();service.reconcile();assertEquals(BillingStatus.READY_FOR_BILLING,existing.getStatus());assertNull(existing.getBillingStartedAt());assertNull(existing.getNextBillingAt());verify(repository).save(existing);}
 @Test void approveStartsBillingWhenAllStepsAreDone(){Subscription existing=subscription(request("Basic"),BillingStatus.READY_FOR_BILLING);when(repository.findByOrderId("order-1")).thenReturn(Optional.of(existing));dependenciesComplete();Subscription approved=service.approve("order-1","Checks passed");assertEquals(BillingStatus.ACTIVE,approved.getStatus());assertNotNull(approved.getBillingStartedAt());assertNotNull(approved.getNextBillingAt());assertEquals("Checks passed",approved.getStatusReason());}
 @Test void approveRefusesUntilSubscriptionIsReady(){when(repository.findByOrderId("order-1")).thenReturn(Optional.of(subscription(request("Basic"),BillingStatus.WAITING_FOR_FULFILLMENT)));dependenciesComplete();assertThrows(ConflictException.class,()->service.approve("order-1",null));verify(repository,never()).save(any());}
 @Test void approveRefusesWhenPaymentIsNotCompleted(){when(repository.findByOrderId("order-1")).thenReturn(Optional.of(subscription(request("Basic"),BillingStatus.READY_FOR_BILLING)));dependenciesComplete();when(dependencies.payment("order-1")).thenReturn(new DependencyClient.DependencyState("payment-1","REFUND_PENDING"));ConflictException error=assertThrows(ConflictException.class,()->service.approve("order-1",null));assertTrue(error.getMessage().contains("payment"));verify(repository,never()).save(any());}
 @Test void rejectRequiresReasonAndStopsBilling(){Subscription existing=subscription(request("Basic"),BillingStatus.READY_FOR_BILLING);when(repository.findByOrderId("order-1")).thenReturn(Optional.of(existing));assertThrows(IllegalArgumentException.class,()->service.reject("order-1"," "));assertEquals(BillingStatus.REJECTED,service.reject("order-1","Customer disputed plan").getStatus());assertEquals("Customer disputed plan",existing.getStatusReason());assertThrows(ConflictException.class,()->service.approve("order-1",null));}
 @Test void rejectIsNotAllowedAfterBillingStarted(){when(repository.findByOrderId("order-1")).thenReturn(Optional.of(subscription(request("Basic"),BillingStatus.ACTIVE)));assertThrows(ConflictException.class,()->service.reject("order-1","too late"));}
 @Test void listsCustomerSubscriptionsFilteredByStatus(){Subscription active=subscription(request("Basic"),BillingStatus.ACTIVE);when(repository.findByCustomerIdAndStatusOrderByCreatedAtDesc("customer-1",BillingStatus.ACTIVE)).thenReturn(List.of(active));assertEquals(List.of(active),service.byCustomer(" customer-1 ",BillingStatus.ACTIVE));verify(repository,never()).findByCustomerIdOrderByCreatedAtDesc(any());}
 @Test void approveSchedulesFirstInvoiceOneCalendarMonthLaterOnADayThatExistsInEveryMonth(){Subscription existing=subscription(request("Basic"),BillingStatus.READY_FOR_BILLING);when(repository.findByOrderId("order-1")).thenReturn(Optional.of(existing));dependenciesComplete();service.approve("order-1",null);java.time.LocalDate expected=java.time.LocalDate.now(java.time.ZoneOffset.UTC).plusMonths(1);assertEquals(expected.atStartOfDay(java.time.ZoneOffset.UTC).toInstant(),existing.getNextBillingAt());assertEquals(Math.min(expected.getDayOfMonth(),28),existing.getBillingDay());}
 @Test void recordBilledPeriodAdvancesOnceAndIsIdempotent(){Subscription existing=subscription(request("Basic"),BillingStatus.ACTIVE);existing.setNextBillingAt(day(2026,10,1));when(repository.findByOrderId("order-1")).thenReturn(Optional.of(existing));service.recordBilledPeriod("order-1",java.time.LocalDate.of(2026,10,1),java.time.LocalDate.of(2026,11,1));assertEquals(day(2026,11,1),existing.getNextBillingAt());service.recordBilledPeriod("order-1",java.time.LocalDate.of(2026,10,1),java.time.LocalDate.of(2026,11,1));verify(repository,times(1)).save(existing);assertThrows(ConflictException.class,()->service.recordBilledPeriod("order-1",java.time.LocalDate.of(2026,9,1),java.time.LocalDate.of(2026,10,1)));}
 @Test void recordBilledPeriodRejectsInactiveSubscriptions(){Subscription existing=subscription(request("Basic"),BillingStatus.CANCELLED);existing.setNextBillingAt(day(2026,10,1));when(repository.findByOrderId("order-1")).thenReturn(Optional.of(existing));assertThrows(ConflictException.class,()->service.recordBilledPeriod("order-1",java.time.LocalDate.of(2026,10,1),java.time.LocalDate.of(2026,11,1)));}
 @Test void billingDayCannotBeSetOnCancelledSubscription(){when(repository.findByOrderId("order-1")).thenReturn(Optional.of(subscription(request("Basic"),BillingStatus.CANCELLED)));assertThrows(ConflictException.class,()->service.changeBillingDay("order-1",5));}
 @Test void dueIncludesTheWholeAsOfDay(){service.due(java.time.LocalDate.of(2026,10,1),0,50);verify(repository).findByStatusAndNextBillingAtBefore(eq(BillingStatus.ACTIVE),eq(day(2026,10,2)),any());}
 private static java.time.Instant day(int y,int m,int d){return java.time.LocalDate.of(y,m,d).atStartOfDay(java.time.ZoneOffset.UTC).toInstant();}
 private void dependenciesComplete(){when(dependencies.payment("order-1")).thenReturn(new DependencyClient.DependencyState("payment-1","COMPLETED"));when(dependencies.activation("order-1")).thenReturn(new DependencyClient.DependencyState("activation-1","ACTIVE"));when(dependencies.fulfillment("order-1")).thenReturn(new DependencyClient.DependencyState("fulfillment-1","DELIVERED"));}
 @Test void createRejectsMismatchedDependencyId(){when(repository.findByOrderId("order-1")).thenReturn(Optional.empty());when(dependencies.activation("order-1")).thenReturn(new DependencyClient.DependencyState("another-activation","ACTIVE"));assertThrows(ConflictException.class,()->service.create(request("Basic")));verify(repository,never()).save(any());}
 @Test void duplicateKeyRaceReturnsEquivalentWinner(){CreateSubscriptionRequest request=request("Basic");Subscription winner=subscription(request,BillingStatus.WAITING_FOR_ACTIVATION);when(repository.findByOrderId("order-1")).thenReturn(Optional.empty(),Optional.of(winner));when(repository.save(any())).thenThrow(new DuplicateKeyException("orderId_1"));assertSame(winner,service.create(request));}
 @Test void cancellationIsIdempotentAndTerminal(){Subscription existing=subscription(request("Basic"),BillingStatus.ACTIVE);when(repository.findByOrderId("order-1")).thenReturn(Optional.of(existing));assertEquals(BillingStatus.CANCELLED,service.cancel("order-1").getStatus());assertEquals(BillingStatus.CANCELLED,service.cancel("order-1").getStatus());verify(repository,times(1)).save(existing);assertThrows(ConflictException.class,()->service.suspend("order-1"));}
 private CreateSubscriptionRequest request(String plan){return new CreateSubscriptionRequest("order-1","customer-1",plan,new BigDecimal("29.99"),"activation-1","fulfillment-1");}
 private Subscription subscription(CreateSubscriptionRequest r,BillingStatus status){Subscription s=new Subscription();s.setOrderId(r.orderId());s.setCustomerId(r.customerId());s.setPlanName(r.planName());s.setMonthlyAmount(r.monthlyAmount());s.setActivationId(r.activationId());s.setFulfillmentId(r.fulfillmentId());s.setStatus(status);return s;}
}
