-- Invoicing schema. Spring Batch creates its own BATCH_* tables alongside these.

-- One row: when the daily invoicing run happens and whether it is enabled.
create table billing_schedule (
    id          int primary key,
    enabled     boolean not null,
    run_time    time not null,
    updated_at  timestamp with time zone not null
);
insert into billing_schedule (id, enabled, run_time, updated_at) values (1, true, '02:00', current_timestamp);

-- Every subscription picked up by a run, snapshotted before invoicing so paging stays stable while billing dates move.
create table billing_run_items (
    id                 bigint generated by default as identity primary key,
    run_id             bigint not null,           -- Spring Batch job instance id
    subscription_id    varchar(64) not null,
    order_id           varchar(64) not null,
    customer_id        varchar(64) not null,
    plan_name          varchar(200) not null,
    monthly_amount     numeric(12, 2) not null,
    billing_day        int not null,
    period_start       date not null,
    state              varchar(20) not null,      -- PENDING, INVOICED, FAILED
    invoice_number     varchar(40),
    message            varchar(1000),
    updated_at         timestamp with time zone not null,
    constraint uq_run_subscription unique (run_id, subscription_id)
);
create index ix_run_items_run_state on billing_run_items (run_id, state, id);

create sequence invoice_number_seq start with 1;

create table invoices (
    id                 bigint generated by default as identity primary key,
    invoice_number     varchar(40) not null unique,
    run_id             bigint not null,
    subscription_id    varchar(64) not null,
    order_id           varchar(64) not null,
    customer_id        varchar(64) not null,
    plan_name          varchar(200) not null,
    period_start       date not null,
    period_end         date not null,
    prorated           boolean not null,
    net_amount         numeric(12, 2) not null,
    vat_rate           numeric(5, 4) not null,
    vat_amount         numeric(12, 2) not null,
    total_amount       numeric(12, 2) not null,
    currency           varchar(3) not null,
    status             varchar(20) not null,      -- ISSUED, PAID, PAYMENT_FAILED
    payment_id         varchar(64),
    payment_reference  varchar(40),
    failure_reason     varchar(1000),
    issued_at          timestamp with time zone not null,
    updated_at         timestamp with time zone not null,
    -- A subscription is invoiced once per period, however many times a run is retried.
    constraint uq_invoice_period unique (subscription_id, period_start)
);
create index ix_invoices_customer on invoices (customer_id, issued_at);
create index ix_invoices_run on invoices (run_id);
