package com.example.orchestration.controller;
import com.example.orchestration.workflow.*;import io.swagger.v3.oas.annotations.Operation;import jakarta.validation.Valid;import io.temporal.client.*;import java.util.Map;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import org.springframework.web.server.ResponseStatusException;
@RestController @RequestMapping("/api/workflows/orders") public class WorkflowController{
 private final WorkflowClient client; private final OrderCancellation cancellation; public WorkflowController(WorkflowClient client,OrderCancellation cancellation){this.client=client;this.cancellation=cancellation;}
 // An order runs through its lifecycle once: REJECT_DUPLICATE stops a finished order (completed, failed or cancelled) from being restarted.
 @PostMapping @Operation(summary="Start an idempotent durable order lifecycle") public ResponseEntity<Map<String,String>> start(@Valid @RequestBody OrderWorkflowRequest request){if(cancellation.isCancelled(request.orderId()))throw new ResponseStatusException(HttpStatus.CONFLICT,"Order is cancelled");String id="order-"+request.orderId();OrderLifecycleWorkflow workflow=client.newWorkflowStub(OrderLifecycleWorkflow.class,WorkflowOptions.newBuilder().setWorkflowId(id).setTaskQueue("order-lifecycle").setWorkflowIdReusePolicy(io.temporal.api.enums.v1.WorkflowIdReusePolicy.WORKFLOW_ID_REUSE_POLICY_REJECT_DUPLICATE).build());try{WorkflowClient.start(workflow::run,request);return ResponseEntity.accepted().body(Map.of("workflowId",id,"status","STARTED"));}catch(WorkflowExecutionAlreadyStarted ignored){return ResponseEntity.ok(Map.of("workflowId",id,"status",workflow.status()));}}
 @PostMapping("/{orderId}/cancel") @Operation(summary="Cancel an order that has not completed",description="Running orders are stopped by the workflow; orders whose workflow never started or failed are compensated directly. Compensation voids or refunds payment, stops delivery and eSIM activation, cancels billing and marks the order CANCELLED. A completed order's subscription is cancelled through billing instead.") public ResponseEntity<Map<String,String>> cancel(@PathVariable String orderId,@Valid @RequestBody CancelOrderRequest request){return ResponseEntity.accepted().body(Map.of("orderId",orderId,"status",cancellation.cancel(orderId,request.reason())));}
 @GetMapping("/{orderId}") @Operation(summary="Query current durable workflow state") public Map<String,String> status(@PathVariable String orderId){String state=cancellation.state(orderId);if("NOT_STARTED".equals(state))throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Workflow not found");return Map.of("workflowId","order-"+orderId,"status",state);}
 /** Always return the reason with the status so the admin UI can show why an action was refused. */
 @ExceptionHandler(ResponseStatusException.class) ResponseEntity<Map<String,Object>> refused(ResponseStatusException e){return ResponseEntity.status(e.getStatusCode()).body(Map.of("status",e.getStatusCode().value(),"message",String.valueOf(e.getReason())));}
}
